"""Agent-Pilot 业务产品层。

M0 阶段提供领域模型、状态机、事件契约与事件底座。
M1 阶段在其上新增服务编排层（services/）与技能层（skills/），
但仍不依赖 LLM、Feishu、FastAPI、`agent_hub.core.AgentPipeline`。
"""

from __future__ import annotations

from agent_hub.pilot.domain.enums import (
    ActorType,
    ApprovalAction,
    ApprovalStatus,
    ApprovalTargetType,
    ArtifactAction,
    ArtifactStatus,
    ArtifactType,
    EventLevel,
    EventType,
    PlanAction,
    PlanStatus,
    PlanStepAction,
    PlanStepKind,
    PlanStepStatus,
    RiskLevel,
    TaskAction,
    TaskStatus,
    WorkspaceAction,
    WorkspaceStatus,
)
from agent_hub.pilot.domain.errors import (
    ConcurrencyConflict,
    IllegalTransition,
    PilotDomainError,
    PlanGraphError,
)
from agent_hub.pilot.domain.events import ExecutionEvent
from agent_hub.pilot.domain.models import (
    Approval,
    Artifact,
    Plan,
    PlanStep,
    Task,
    Workspace,
)
from agent_hub.pilot.domain.state import transition, validate_plan_graph
from agent_hub.pilot.events.bus import EventBus, EventSubscription
from agent_hub.pilot.events.store import (
    EventStore,
    InMemoryEventStore,
    SnapshotStore,
    SQLiteEventStore,
)
from agent_hub.pilot.services import (
    ApprovalService,
    ArtifactStore,
    BriefRevisionContext,
    CommandError,
    ExecutionEngine,
    FakeModelGateway,
    ModelGateway,
    OpenAIModelGateway,
    PilotCommandService,
    PilotEventPublisher,
    PilotQueryService,
    PilotRepository,
    PlanBlueprint,
    PlanContext,
    PlanningService,
    PlanProfile,
    PlanStepDraft,
    PlanTemplateError,
    RunResult,
    ServiceActor,
    StepExecution,
    StepInputResolver,
    TaskDetail,
    TaskHandle,
    TaskOrchestrator,
    TaskProgressReporter,
    TaskRequest,
    TaskSummary,
    TemplatePlanGateway,
    WorkspaceSummary,
)
from agent_hub.pilot.skills import (
    BRIEF_SECTIONS,
    ArtifactContentReader,
    BriefGenerator,
    DryRunUnsupported,
    RegisteredSkill,
    SkillFunc,
    SkillInvocation,
    SkillNotFound,
    SkillRegistry,
    SkillResult,
    SkillSpec,
    TemplateBriefGenerator,
    register_fake_skills,
    register_internal_document_skills,
)

__all__ = [
    # enums
    "ActorType",
    "ApprovalAction",
    "ApprovalStatus",
    "ApprovalTargetType",
    "ArtifactAction",
    "ArtifactStatus",
    "ArtifactType",
    "EventLevel",
    "EventType",
    "PlanAction",
    "PlanStatus",
    "PlanStepAction",
    "PlanStepKind",
    "PlanStepStatus",
    "RiskLevel",
    "TaskAction",
    "TaskStatus",
    "WorkspaceAction",
    "WorkspaceStatus",
    # errors
    "ConcurrencyConflict",
    "IllegalTransition",
    "PilotDomainError",
    "PlanGraphError",
    "PlanTemplateError",
    # domain models / events
    "Approval",
    "Artifact",
    "ExecutionEvent",
    "Plan",
    "PlanStep",
    "Task",
    "Workspace",
    # state
    "transition",
    "validate_plan_graph",
    # event底座
    "EventBus",
    "EventStore",
    "EventSubscription",
    "InMemoryEventStore",
    "SnapshotStore",
    "SQLiteEventStore",
    # M1 services
    "ApprovalService",
    "ArtifactStore",
    "ExecutionEngine",
    "FakeModelGateway",
    "ModelGateway",
    "OpenAIModelGateway",
    "PilotEventPublisher",
    "PilotRepository",
    "PlanBlueprint",
    "PlanContext",
    "PlanProfile",
    "PlanStepDraft",
    "PlanningService",
    "RunResult",
    "ServiceActor",
    "StepExecution",
    "TaskHandle",
    "TaskOrchestrator",
    "TaskProgressReporter",
    "TaskRequest",
    "TemplatePlanGateway",
    # M2 services
    "CommandError",
    "PilotCommandService",
    "PilotQueryService",
    "TaskDetail",
    "TaskSummary",
    "WorkspaceSummary",
    # M1 skills
    "BRIEF_SECTIONS",
    "ArtifactContentReader",
    "BriefGenerator",
    "BriefRevisionContext",
    "DryRunUnsupported",
    "RegisteredSkill",
    "SkillFunc",
    "SkillInvocation",
    "SkillNotFound",
    "SkillRegistry",
    "SkillResult",
    "SkillSpec",
    "StepInputResolver",
    "TemplateBriefGenerator",
    "register_fake_skills",
    "register_internal_document_skills",
]

